get http://localhost:3000/products
###

GET http://localhost:3000/products/11.json


###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "gigantic huge table",
  "price": 100,
  "image_url": "table.com",
  "description": "a gigantic huge table surface"
}
###
PATCH http://localhost:3000/products/13.json
Content-Type: application/json

{
  "name": "The Big huge gigantic tabl"
}
###
DELETE http://localhost:3000/products/8