get http://localhost:3000/products
###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "chair",
  "price": 20,
  "image_url": "chair.com",
  "description": "sit on it"
}
###
PATCH http://localhost:3000/products/7
Content-Type: application/json

{
  "name": "Big Recliner",
  "price": 50,
  "image_url": "recliner.com",
  "description": "sit back and relax dude"
}