get http://localhost:3000/products
###

GET http://localhost:3000/products/11


###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "huge table",
  "price": 25,
  "image_url": "table.com",
  "description": "a huge table surface"
}
###
PATCH http://localhost:3000/products/7
Content-Type: application/json

{
  "name": "The Big Recliner"
}
###
DELETE http://localhost:3000/products/8